#!/usr/bin/env python3
"""从 docs/dev/09-admin-api.md §4bis 生成 params_gen.go。

为什么生成而不手写：§4bis 那张表是 config_params 种子与 /admin/config 白名单的
**唯一真相源**（09 §4bis 原文）。手抄必然漂移，而漂移的后果是运行时
静默取零值 —— catalog_missing_rounds=0 就会让每轮采集都判模型下架。

用法：make gen-params（或 python3 internal/config/gen_params.py）
CI 校验：生成后 git diff 必须为空，否则说明文档改了没重新生成。
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "docs/dev/09-admin-api.md"
OUT = ROOT / "internal/config/params_gen.go"

def clean_default(cell: str) -> str:
    """剥掉表格单元里的 Markdown 装饰，只留值本身。

    ⚠️ 首版没做这件事，于是 `false` 带着反引号进了生成物 —— 五个布尔项的默认值
    变成字面量 "`false`"，inferKind 判成字符串、Snapshot.Bool() 直接解析失败，
    而 Validate 因为判成字符串而不检查它，问题会一直潜伏到运行时真去读那个键。
    """
    s = cell.strip()
    # 去粗体/斜体标记
    s = re.sub(r"\*\*(.+?)\*\*", r"\1", s)
    # 整体被反引号包住 → 取内容（数组类默认值 `["a","b"]` 也走这条）
    m = re.fullmatch(r"`(.+)`", s)
    if m:
        s = m.group(1)
    s = s.strip()
    # `""` 表示空字符串默认值（如 alert_webhook_url：为空则不外发）。
    # 文档里若写"空"这类中文字样，种子会把它当字面量入库 —— P3 的 webhook
    # 代码就会拿到一个名为"空"的 URL 去 POST。故只认 `""` 这一种写法。
    if s == '""':
        return ""
    return s



seg_all = SRC.read_text()
seg = seg_all[seg_all.index("## 4bis."): seg_all.index("## 4ter.")]

rows, group = [], None
for line in seg.split("\n"):
    g = re.match(r"^\|\s*\*\*(.+?)\*\*\s*\|", line)
    if g and "`" not in g.group(1):
        group = re.sub(r"（.*?）", "", g.group(1)).strip()
        continue
    if not line.startswith("|"):
        continue
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    if not cells or not re.fullmatch(r"`[a-z0-9_]+`", cells[0]):
        continue
    raw_default = cells[1] if len(cells) > 1 else ""
    rows.append({
        "key": cells[0].strip("`"),
        "default": clean_default(raw_default),
        "critical": len(cells) > 2 and "✅" in cells[2],
        "group": group or "",
        # env 来源的项不落 config_params（09 §4bis 对 admin_token 的原文：
        # "不落 config_params（避免自己改自己）；此处仅登记其存在"）。
        # 不排除会导致：管理 API 能改自己的鉴权令牌 = 提权。
        "env_sourced": "env" in raw_default and "注入" in raw_default,
    })

assert rows, "未从 §4bis 提取到任何键——文档结构可能变了"
keys = [r["key"] for r in rows]
assert len(keys) == len(set(keys)), "§4bis 存在重复键"


def go_lit(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// Code generated by internal/config/gen_params.py; DO NOT EDIT.",
    "//",
    "// 源：docs/dev/09-admin-api.md §4bis（config_params 键清单的唯一真相源）。",
    "// 改配置项请改文档再跑 `make gen-params`，不要直接编辑本文件。",
    "",
    "package config",
    "",
    "// ParamSpec 是一个配置项的静态元数据（09 §4 ParamMeta 的落地形态）。",
    "type ParamSpec struct {",
    "\tKey      string",
    "\tDefault  string // 文档声明的默认值，已剥离 Markdown 装饰",
    "\tCritical bool   // is_critical：修改需二次确认（FR-115）",
    "\tGroup    string // 设置页分组",
    "\t// EnvSourced：值由环境变量注入，**不落 config_params**。",
    "\t// 目前只有 admin_token（09 §4bis：避免自己改自己）——若把它写进表，",
    "\t// 管理 API 就能改自己的鉴权令牌，等于提权。种子与快照都必须跳过它。",
    "\tEnvSourced bool",
    "}",
    "",
    f"// Params 是全部 {len(rows)} 个配置项，顺序与文档一致。",
    "var Params = []ParamSpec{",
]
for r in rows:
    lines.append(
        "\t{Key: %s, Default: %s, Critical: %s, Group: %s, EnvSourced: %s},"
        % (go_lit(r["key"]), go_lit(r["default"]),
           "true" if r["critical"] else "false", go_lit(r["group"]),
           "true" if r["env_sourced"] else "false")
    )
lines += ["}", ""]

OUT.write_text("\n".join(lines))
print(f"生成 {OUT.relative_to(ROOT)}：{len(rows)} 键，"
      f"{sum(1 for r in rows if r['critical'])} 个关键项")
