#!/usr/bin/env python3
"""从 docs/dev/09-admin-api.md §4bis 生成 params_gen.go。

为什么生成而不手写：§4bis 那张表是 config_params 种子与 /admin/config 白名单的
**唯一真相源**（09 §4bis 原文）。手抄 72 行必然漂移，而漂移的后果是运行时
静默取零值 —— catalog_missing_rounds=0 就会让每轮采集都判模型下架。

用法：make gen-params（或 python3 internal/config/gen_params.py）
CI 校验：生成后 git diff 必须为空，否则说明文档改了没重新生成。
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "docs/dev/09-admin-api.md"
OUT = ROOT / "internal/config/params_gen.go"

seg_all = SRC.read_text()
seg = seg_all[seg_all.index("## 4bis."): seg_all.index("## 5.")]

rows, group = [], None
for line in seg.split("\n"):
    g = re.match(r"^\|\s*\*\*(.+?)\*\*\s*\|", line)
    if g and "`" not in g.group(1):
        group = re.sub(r"（.*?）", "", g.group(1)).strip()
        continue
    if not line.startswith("|"):
        continue
    cells = [c.strip() for c in line.strip().strip("|").split("|")]
    if not cells or not re.fullmatch(r"`[a-z0-9_]+`", cells[0]):
        continue
    rows.append({
        "key": cells[0].strip("`"),
        "default": cells[1] if len(cells) > 1 else "",
        "critical": len(cells) > 2 and "✅" in cells[2],
        "group": group or "",
    })

assert rows, "未从 §4bis 提取到任何键——文档结构可能变了"
keys = [r["key"] for r in rows]
assert len(keys) == len(set(keys)), "§4bis 存在重复键"


def go_lit(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


lines = [
    "// Code generated by internal/config/gen_params.py; DO NOT EDIT.",
    "//",
    "// 源：docs/dev/09-admin-api.md §4bis（config_params 键清单的唯一真相源）。",
    "// 改配置项请改文档再跑 `make gen-params`，不要直接编辑本文件。",
    "",
    "package config",
    "",
    "// ParamSpec 是一个配置项的静态元数据（09 §4 ParamMeta 的落地形态）。",
    "type ParamSpec struct {",
    "\tKey      string",
    "\tDefault  string // 文档声明的默认值，原样保留（解析交给使用方）",
    "\tCritical bool   // is_critical：修改需二次确认（FR-115）",
    "\tGroup    string // 设置页分组",
    "}",
    "",
    f"// Params 是全部 {len(rows)} 个配置项，顺序与文档一致。",
    "var Params = []ParamSpec{",
]
for r in rows:
    lines.append(
        "\t{Key: %s, Default: %s, Critical: %s, Group: %s},"
        % (go_lit(r["key"]), go_lit(r["default"]),
           "true" if r["critical"] else "false", go_lit(r["group"]))
    )
lines += ["}", ""]

OUT.write_text("\n".join(lines))
print(f"生成 {OUT.relative_to(ROOT)}：{len(rows)} 键，"
      f"{sum(1 for r in rows if r['critical'])} 个关键项")
