// Code generated by internal/config/gen_params.py; DO NOT EDIT.
//
// 源：docs/dev/09-admin-api.md §4bis（config_params 键清单的唯一真相源）。
// 改配置项请改文档再跑 `make gen-params`，不要直接编辑本文件。

package config

// ParamSpec 是一个配置项的静态元数据（09 §4 ParamMeta 的落地形态）。
type ParamSpec struct {
	Key      string
	Default  string // 文档声明的默认值，已剥离 Markdown 装饰
	Critical bool   // is_critical：修改需二次确认（FR-115）
	Group    string // 设置页分组
	// EnvSourced：值由环境变量注入，**不落 config_params**。
	// 目前只有 admin_token（09 §4bis：避免自己改自己）——若把它写进表，
	// 管理 API 就能改自己的鉴权令牌，等于提权。种子与快照都必须跳过它。
	EnvSourced bool
}

// Params 是全部 72 个配置项，顺序与文档一致。
var Params = []ParamSpec{
	{Key: "default_ttft_budget_ms", Default: "8000", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "prefix_target_ms", Default: "10000", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "ttft_safety_margin_ms", Default: "500", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "min_hop_ms", Default: "1500", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "max_hops", Default: "3", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "price_stale_hours", Default: "48", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "snapshot_refresh_ms", Default: "1000", Critical: false, Group: "调度与期限", EnvSourced: false},
	{Key: "cache_switch_min_hit_rate", Default: "0.6", Critical: false, Group: "缓存", EnvSourced: false},
	{Key: "canary_max_per_hour", Default: "20", Critical: false, Group: "canary", EnvSourced: false},
	{Key: "canary_max_concurrent", Default: "1", Critical: false, Group: "canary", EnvSourced: false},
	{Key: "canary_failure_threshold", Default: "3", Critical: false, Group: "canary", EnvSourced: false},
	{Key: "probe_idle_window_min", Default: "30", Critical: false, Group: "主动测活", EnvSourced: false},
	{Key: "probe_batch_size", Default: "3", Critical: false, Group: "主动测活", EnvSourced: false},
	{Key: "probe_global_cost_cap_ratio", Default: "0.02", Critical: true, Group: "主动测活", EnvSourced: false},
	{Key: "probe_binding_daily_cap", Default: "20", Critical: false, Group: "主动测活", EnvSourced: false},
	{Key: "probe_tenant_cost_cap_ratio", Default: "0.02", Critical: true, Group: "主动测活", EnvSourced: false},
	{Key: "probe_user_cost_cap_ratio", Default: "0.02", Critical: true, Group: "主动测活", EnvSourced: false},
	{Key: "probe_session_cap", Default: "1", Critical: false, Group: "主动测活", EnvSourced: false},
	{Key: "probe_error_budget_ratio", Default: "0.10", Critical: true, Group: "主动测活", EnvSourced: false},
	{Key: "capacity_ceiling_normal", Default: "0.65", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "capacity_ceiling_committed", Default: "0.85", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "capacity_ceiling_takeover", Default: "0.95", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "capacity_ceiling_probe", Default: "0.70", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "balance_safety_reserve_ratio", Default: "0.02", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "balance_text_patterns", Default: "[\"余额\",\"额度\",\"欠费\",\"insufficient\",\"quota\"]", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "balance_safety_reserve_min_usd", Default: "1.0", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "balance_hours_warn", Default: "24", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "balance_hours_stop_probe", Default: "6", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "balance_hours_critical", Default: "1", Critical: false, Group: "容量保留", EnvSourced: false},
	{Key: "retention_months", Default: "7", Critical: true, Group: "容量保留", EnvSourced: false},
	{Key: "health_min_samples_1h", Default: "20", Critical: false, Group: "健康与冷却", EnvSourced: false},
	{Key: "health_min_samples_24h", Default: "100", Critical: false, Group: "健康与冷却", EnvSourced: false},
	{Key: "cooldown_base_sec", Default: "300", Critical: false, Group: "健康与冷却", EnvSourced: false},
	{Key: "cooldown_max_sec", Default: "14400", Critical: false, Group: "健康与冷却", EnvSourced: false},
	{Key: "observing_min_minutes", Default: "30", Critical: false, Group: "健康与冷却", EnvSourced: false},
	{Key: "observing_min_success", Default: "50", Critical: false, Group: "健康与冷却", EnvSourced: false},
	{Key: "domain_min_bindings", Default: "3", Critical: false, Group: "故障域", EnvSourced: false},
	{Key: "domain_fail_ratio", Default: "0.6", Critical: false, Group: "故障域", EnvSourced: false},
	{Key: "domain_disable_sec", Default: "600", Critical: false, Group: "故障域", EnvSourced: false},
	{Key: "alert_close_after_sec", Default: "900", Critical: false, Group: "告警生命周期", EnvSourced: false},
	{Key: "billing_variance_tolerance", Default: "0.05", Critical: true, Group: "配额与计费", EnvSourced: false},
	{Key: "billing_min_base_usd", Default: "0.01", Critical: false, Group: "配额与计费", EnvSourced: false},
	{Key: "billing_abs_tolerance_usd", Default: "0.05", Critical: false, Group: "配额与计费", EnvSourced: false},
	{Key: "billing_recovery_streak", Default: "20", Critical: false, Group: "配额与计费", EnvSourced: false},
	{Key: "alert_webhook_url", Default: "", Critical: true, Group: "告警", EnvSourced: false},
	{Key: "alert_recovery_checks", Default: "3", Critical: false, Group: "告警", EnvSourced: false},
	{Key: "key_invalid_streak", Default: "3", Critical: false, Group: "告警", EnvSourced: false},
	{Key: "all_unavail_checks", Default: "2", Critical: false, Group: "告警", EnvSourced: false},
	{Key: "error_budget_burn_ratio", Default: "0.5", Critical: false, Group: "告警", EnvSourced: false},
	{Key: "stale_alert_hours", Default: "12", Critical: false, Group: "告警", EnvSourced: false},
	{Key: "collector_request_interval_ms", Default: "200", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_price_interval_h", Default: "6", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_balance_interval_min", Default: "5", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_keyquota_interval_min", Default: "30", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_catalog_interval_h", Default: "12", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "catalog_missing_rounds", Default: "3", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "sync_min_interval_s", Default: "60", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "takeover_buffer_max_bytes", Default: "262144", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "takeover_buffer_max_ms", Default: "5000", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "cancel_cost_safety_ratio", Default: "1.3", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "tenant_probe_concurrency", Default: "1", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "debug_capture_enabled", Default: "false", Critical: true, Group: "执行面", EnvSourced: false},
	{Key: "debug_capture_max_requests", Default: "20", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "debug_capture_max_bytes", Default: "1048576", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "debug_capture_ttl_minutes", Default: "30", Critical: false, Group: "执行面", EnvSourced: false},
	{Key: "data_policy_enabled", Default: "false", Critical: true, Group: "开关", EnvSourced: false},
	{Key: "alias_passthrough", Default: "false", Critical: true, Group: "开关", EnvSourced: false},
	{Key: "load_test_mode", Default: "false", Critical: true, Group: "开关", EnvSourced: false},
	{Key: "ledger_batch_commit_enabled", Default: "false", Critical: false, Group: "开关", EnvSourced: false},
	{Key: "ledger_batch_commit_max_size", Default: "16", Critical: false, Group: "开关", EnvSourced: false},
	{Key: "ledger_batch_commit_linger_ms", Default: "2", Critical: false, Group: "开关", EnvSourced: false},
	{Key: "admin_token", Default: "由 env `ADMIN_TOKEN` 注入", Critical: true, Group: "开关", EnvSourced: true},
}
