// Code generated by internal/config/gen_params.py; DO NOT EDIT.
//
// 源：docs/dev/09-admin-api.md §4bis（config_params 键清单的唯一真相源）。
// 改配置项请改文档再跑 `make gen-params`，不要直接编辑本文件。

package config

// ParamSpec 是一个配置项的静态元数据（09 §4 ParamMeta 的落地形态）。
type ParamSpec struct {
	Key      string
	Default  string // 文档声明的默认值，已剥离 Markdown 装饰
	Critical bool   // is_critical：修改需二次确认（FR-115）
	Group    string // 设置页分组
	// EnvSourced：值由环境变量注入，**不落 config_params**。
	// 目前只有 admin_token（09 §4bis：避免自己改自己）——若把它写进表，
	// 管理 API 就能改自己的鉴权令牌，等于提权。种子与快照都必须跳过它。
	EnvSourced bool
}

// Params 是全部 8 个配置项，顺序与文档一致。
var Params = []ParamSpec{
	{Key: "collector_request_interval_ms", Default: "200", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_price_interval_h", Default: "6", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_balance_interval_min", Default: "5", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_keyquota_interval_min", Default: "30", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "collector_catalog_interval_h", Default: "12", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "catalog_missing_rounds", Default: "3", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "sync_min_interval_s", Default: "60", Critical: false, Group: "采集", EnvSourced: false},
	{Key: "admin_token", Default: "由 env `ADMIN_TOKEN` 注入", Critical: true, Group: "管理鉴权", EnvSourced: true},
}
